"""Education Retrieval + Retention + Learner Model + Elaboration + Construction + Analysis + Environment + Visual Amplifiers [CARD-242..249]."""

from src.application.education.srs import SRS_INTERVALS_DAYS, next_due_after_grade
from src.application.education.quiz_engine import (
    extract_quiz_items_from_note,
    grade_answer_binary,
)
from src.application.education.learner_model import (
    LEARNER_ENTITY,
    LEARNER_CATEGORY,
    select_quiz_items,
    build_ask_pressure_clause,
    summarize_learner_model,
    record_learner_from_grade,
)
from src.application.education.elaboration import (
    ELABORATION_ENTITY,
    ELABORATION_CATEGORY,
    extract_elaboration_items_from_note,
    grade_elaboration_binary,
    grade_and_record_elaboration,
    elaboration_from_mastery_row,
    build_elaboration_ask_clause,
)
from src.application.education.application import (
    APPLICATION_ENTITY,
    APPLICATION_CATEGORY,
    APPLICATION_KIND,
    extract_application_items_from_note,
    grade_application_binary,
    grade_and_record_application,
    mint_exercise_job,
    build_exercise_job_intent,
    build_application_ask_clause,
    application_from_mastery_row,
)

from src.application.education.construction import (
    ARTIFACT_KIND,
    CONSTRUCTION_WIKI_TOOLS,
    construct_study_artifact,
    build_construction_ask_clause,
    build_study_artifact_markdown,
)

from src.application.education.analysis import (
    ANALYSIS_ENTITY,
    ANALYSIS_CATEGORY,
    classify_miss_reason,
    record_error_and_metacog,
    select_quiz_with_miss_reason_pressure,
    list_error_log,
    list_metacog_patterns,
    summarize_analysis,
    build_analysis_ask_clause,
    write_analysis_wiki_outcome,
)


from src.application.education.visual_amplifiers import (
    AMPLIFIER_ENTITY,
    AMPLIFIER_CATEGORY,
    VisualsOnlyRejected,
    extract_amplifiers_from_note,
    attach_amplifier_to_retrieval,
    get_amplifier_for_item,
    amplify_quiz_items,
    build_amplifier_ask_clause,
    refuse_visuals_only,
    summarize_amplifiers,
    build_step_through,
    extract_mermaid_blocks,
)

from src.application.education.environment import (
    ENVIRONMENT_ENTITY,
    ENVIRONMENT_CATEGORY,
    DELIVERY_PROFILES,
    list_delivery_profiles,
    get_delivery_profile,
    select_delivery_profile,
    get_active_delivery_profile,
    shape_quiz_presentation,
    apply_delivery_to_ask,
    build_environment_ask_clause,
    summarize_environment,
)

__all__ = [
    "SRS_INTERVALS_DAYS",
    "next_due_after_grade",
    "extract_quiz_items_from_note",
    "grade_answer_binary",
    "LEARNER_ENTITY",
    "LEARNER_CATEGORY",
    "select_quiz_items",
    "build_ask_pressure_clause",
    "summarize_learner_model",
    "record_learner_from_grade",
    "ELABORATION_ENTITY",
    "ELABORATION_CATEGORY",
    "extract_elaboration_items_from_note",
    "grade_elaboration_binary",
    "grade_and_record_elaboration",
    "elaboration_from_mastery_row",
    "build_elaboration_ask_clause",
    "ARTIFACT_KIND",
    "CONSTRUCTION_WIKI_TOOLS",
    "construct_study_artifact",
    "build_construction_ask_clause",
    "build_study_artifact_markdown",
    "APPLICATION_ENTITY",
    "APPLICATION_CATEGORY",
    "APPLICATION_KIND",
    "extract_application_items_from_note",
    "grade_application_binary",
    "grade_and_record_application",
    "mint_exercise_job",
    "build_exercise_job_intent",
    "build_application_ask_clause",
    "application_from_mastery_row",
    "ANALYSIS_ENTITY",
    "ANALYSIS_CATEGORY",
    "classify_miss_reason",
    "record_error_and_metacog",
    "select_quiz_with_miss_reason_pressure",
    "list_error_log",
    "list_metacog_patterns",
    "summarize_analysis",
    "build_analysis_ask_clause",
    "write_analysis_wiki_outcome",
    "ENVIRONMENT_ENTITY",
    "ENVIRONMENT_CATEGORY",
    "DELIVERY_PROFILES",
    "list_delivery_profiles",
    "get_delivery_profile",
    "select_delivery_profile",
    "get_active_delivery_profile",
    "shape_quiz_presentation",
    "apply_delivery_to_ask",
    "build_environment_ask_clause",
    "summarize_environment",
    "AMPLIFIER_ENTITY",
    "AMPLIFIER_CATEGORY",
    "VisualsOnlyRejected",
    "extract_amplifiers_from_note",
    "attach_amplifier_to_retrieval",
    "get_amplifier_for_item",
    "amplify_quiz_items",
    "build_amplifier_ask_clause",
    "refuse_visuals_only",
    "summarize_amplifiers",
    "build_step_through",
    "extract_mermaid_blocks",
]
