"""
Autonomous Homelab Domain Orchestration Recipe & Topology Generator [CARD-206, REQ-HOMELAB-001, REQ-HOMELAB-002, REQ-HOMELAB-003, REQ-HOMELAB-006].

Provides declarative OpenTofu HCL generation enforcing network isolation invariants,
and structured 4-chapter workflow recipe definitions for fleet orchestration.
"""

from __future__ import annotations

from typing import Any, Dict


def generate_domain_topology_hcl(
    domain_name: str = "lab.local",
    subnet: str = "10.10.10.0/24",
    switch_name: str = "DomainSwitch",
) -> str:
    """
    Generate declarative OpenTofu HCL configuration for isolated Windows domain homelab.

    Guarantees:
    - Dedicated isolated virtual switch (Internal switch_type, NEVER host bridge or external).
    - 3 Gen2 Virtual Machines: DC01, DC02 (Domain Controllers), and FS01 (File Server).
    - Subnet isolation on target subnet (e.g. 10.10.10.0/24).
    """
    return f'''# Autonomous Homelab Domain Topology (Generated by Homelab Fleet)
# Domain: {domain_name}
# Subnet: {subnet}
# Switch: {switch_name}

terraform {{
  required_version = ">= 1.6.0"
  required_providers {{
    hyperv = {{
      source  = "taliesins/hyperv"
      version = ">= 1.0.4"
    }}
  }}
}}

variable "hyperv_user" {{
  type        = string
  description = "Hyper-V administrative user"
  default     = ""
}}

variable "hyperv_password" {{
  type        = string
  description = "Hyper-V administrative password"
  sensitive   = true
  default     = ""
}}

variable "hyperv_host" {{
  type        = string
  description = "Hyper-V host hostname or IP"
  default     = "127.0.0.1"
}}

variable "hyperv_port" {{
  type        = number
  description = "WinRM port for Hyper-V management"
  default     = 5985
}}

provider "hyperv" {{
  user     = var.hyperv_user
  password = var.hyperv_password
  host     = var.hyperv_host
  port     = var.hyperv_port
}}

# Isolated Internal Virtual Switch (Guards host physical adapters from isolation breach)
resource "hyperv_vmswitch" "domain_switch" {{
  name        = "{switch_name}"
  switch_type = "Internal"
  notes       = "Private isolated lab virtual switch for {domain_name} ({subnet})"
}}

# Primary Domain Controller
resource "hyperv_machine_instance" "dc01" {{
  name                 = "DC01"
  generation = 2
  processor_count      = 2
  static_memory        = true
  memory_startup_bytes = 4294967296
  notes                = "Primary Active Directory Domain Controller for {domain_name}"

  network_adaptors {{
    name        = "Ethernet"
    switch_name = hyperv_vmswitch.domain_switch.name
  }}
}}

# Secondary Domain Controller (High Availability)
resource "hyperv_machine_instance" "dc02" {{
  name                 = "DC02"
  generation = 2
  processor_count      = 2
  static_memory        = true
  memory_startup_bytes = 4294967296
  notes                = "Replica Active Directory Domain Controller for {domain_name}"

  network_adaptors {{
    name        = "Ethernet"
    switch_name = hyperv_vmswitch.domain_switch.name
  }}
}}

# Member File Server
resource "hyperv_machine_instance" "fs01" {{
  name                 = "FS01"
  generation = 2
  processor_count      = 2
  static_memory        = true
  memory_startup_bytes = 4294967296
  notes                = "Domain Member File Server for {domain_name}"

  network_adaptors {{
    name        = "Ethernet"
    switch_name = hyperv_vmswitch.domain_switch.name
  }}
}}

output "domain_switch_name" {{
  value = hyperv_vmswitch.domain_switch.name
}}

output "domain_subnet" {{
  value = "{subnet}"
}}

output "vm_instances" {{
  value = [
    hyperv_machine_instance.dc01.name,
    hyperv_machine_instance.dc02.name,
    hyperv_machine_instance.fs01.name,
  ]
}}
'''


def get_homelab_domain_workflow_recipe() -> Dict[str, Any]:
    """
    Return the 4-chapter workflow recipe for autonomous Windows domain homelab provisioning [REQ-HOMELAB-001, REQ-HOMELAB-006].
    """
    return {
        "name": "homelab-domain-deployment",
        "owner_agent_id": "homelab",
        "description": "Multi-agent autonomous provisioning recipe for isolated Windows domain homelab on Hyper-V.",
        "chapters": [
            {
                "name": "Platform & Switch Verification",
                "kind": "handoff",
                "assigned_agent_id": "homelab-admin",
                "handoff_target_agent_id": "homelab-admin",
                "success_rule": "Host virtualization capacity, RAM, and DomainSwitch isolation verified with zero host physical adapter changes.",
            },
            {
                "name": "Domain Architecture Blueprint",
                "kind": "handoff",
                "assigned_agent_id": "homelab-architect",
                "handoff_target_agent_id": "homelab-architect",
                "success_rule": "Verified architecture specs for DC01, DC02, FS01 on 10.10.10.0/24 subnet committed to homelab wiki.",
            },
            {
                "name": "IaC Authoring & Compiler Self-Correction",
                "kind": "handoff",
                "assigned_agent_id": "homelab-engineer",
                "handoff_target_agent_id": "homelab-engineer",
                "success_rule": "OpenTofu HCL code validated via compiler feedback with zero errors and dry-run plan generated.",
            },
            {
                "name": "Final Review & Dry-Run Plan Approval",
                "kind": "handoff",
                "assigned_agent_id": "homelab-admin",
                "handoff_target_agent_id": "homelab-admin",
                "success_rule": "Dry-run plan verified by Homelab Admin and presented for human approval gate before apply.",
            },
        ],
    }
